NAV-416. Added a column property to disable markdown.
Tradeshift/tradeshift-ui pull request #965
Opened 2020-10-21 17:00 UTC by aleks-elkin

@Tradeshift/TradeshiftUI

Fixes issue #964

Added a new boolean property `disableMarkdown` to a column config so developer can completely disable Markdown processing of the cell's content in this column.

![Screenshot 2020-10-21 at 18 58 27](https://user-images.githubusercontent.com/55530374/96753039-94c49000-13cf-11eb-8dff-e7f2547042bb.png)

2020-10-22 08:42 UTC, esmailpour-hosein requested changes
I think we should choose a different approach. 
We should do a similar thing as visible or sortable properties of table col model: https://github.com/Tradeshift/tradeshift-ui/blob/master/src/runtime/js/ts.ui/tables/tables-api%40tradeshift.com/models/cols/ts.ui.TableColModel.js

So, let's say we add `markdown` or `markdownFormatting` to the model with default value of true, and then let it be disabled. 

Another note, I think we should add it to the table level as well, so like `linkable` we should have a `disableMarkdown` method that easily disable it for the whole table.

2020-10-23 10:55 UTC, esmailpour-hosein approved these changes
Nice job! LGTM 👍 
@ehats Can you please take a look at this PR?

2020-10-23 10:56 UTC, ehats approved these changes

2020-10-23 10:56 UTC, ehats commented
:rocket:

2020-10-23 11:01 UTC, merged